language: node_js
before_install:
  - cd SMAS-System
  - git fetch --unshallow
node_js:
  - "node"

branches:
  except:
    - development

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true