language: node_js
before_install:
  - cd SMAS-System
  - git fetch --unshallow
node_js:
  - "node"
addons:
  apt:
    packages:
      - google-chrome-stable

script: npm run ci

branches:
  except:
    - development

deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on:
    branch: master